apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale-test
  namespace: jenkins-agents
spec:
  replicas: 1
  selector:
    matchLabels:
      run: autoscale-test
  template:
    metadata:
      labels:
        run: autoscale-test
    spec:
      containers:
      - name: reserve-resources-1
        image: k8s.gcr.io/pause
        resources:
          requests:
            memory: "2Gi"
            cpu: "850m"
