apiVersion: apps/v1
kind: Deployment
metadata:
  name: overprovisioning
  namespace: jenkins-agents
spec:
  replicas: 1
  selector:
    matchLabels:
      run: overprovisioning
  template:
    metadata:
      labels:
        run: overprovisioning
    spec:
      priorityClassName: overprovisioning
      containers:
      - name: reserve-resources-1
        image: k8s.gcr.io/pause
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
      nodeSelector:
        cjeType: agent
